name = "your-monorepo-backend-name"
main = "server/dist/index.js"
compatibility_date = "2025-05-19"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[build]
command = "bun run build:server"
watch_dir = "server/src"

[vars]
R2_PUBLIC_URL = "https://pub-eb8bc14505da4173971fab0835943824.r2.dev"
R2_PUBLIC_URL_PREVIEW = "https://pub-f13c8ed5c4ed4bf990ca088c26785c34.r2.dev"

[[d1_databases]]
binding = "DB"
database_name = "my-d1-db"
database_id = "d4c47bf8-8b65-46fa-bcf2-5e85730ff4c5"
preview_database_id = "d4c47bf8-8b65-46fa-bcf2-5e85730ff4c5"
migrations_dir = "server/migrations"

[[r2_buckets]]
binding = "MY_R2_BUCKET"
bucket_name = "problemimage"
preview_bucket_name = "problemimage-preview"

# 예시: 환경별 설정 (필요한 경우 주석 해제 후 값 수정)
# [env.staging]
# name = "your-monorepo-backend-name-staging"
# vars = { STAGE = "staging" }
# [[d1_databases]]
# binding = "DB"
# database_name = "my-d1-db-staging"
# database_id = "your_staging_database_id"
# preview_database_id = "your_staging_preview_database_id"
#
# [env.production]
# # name 필드는 기본 name을 사용하거나 프로덕션 전용 이름을 지정할 수 있습니다.
# # name = "your-monorepo-backend-name-production"
# vars = { STAGE = "production" }
# # 프로덕션 환경의 바인딩 설정은 기본 설정을 따르거나 여기서 재정의할 수 있습니다.
# # [[d1_databases]]
# # binding = "DB"
# # database_name = "my-d1-db"
# # database_id = "d4c47bf8-8b65-46fa-bcf2-5e85730ff4c5" # 실제 프로덕션 ID